
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build"

# Process files automatically
[build.processing]
  skip_processing = false

# Environment variables
[build.environment]
  NODE_VERSION = "18.0.0"

# Global headers for caching control
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
