
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build"

# Disable asset optimization
[build.processing]
  skip_processing = true

# Global headers for all paths
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Primary SPA redirect - this is critical for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific path handling for sovereign-access
[[headers]]
  for = "/sovereign-access/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
