
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build"

# Process files automatically
[build.processing]
  skip_processing = false

# Environment variables
[build.environment]
  NODE_VERSION = "18.0.0"

# Add aggressive cache invalidation
[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    X-Content-Type-Options = "nosniff"
    Clear-Site-Data = "*"

# More specific caching for index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# SPA redirect with cache control
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {Cache-Control = "no-store, no-cache, must-revalidate", X-From = "Netlify"}
