
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build"
  ignore_warnings = true

# Disable all processing to prevent automatic optimizations that might cause caching
[build.processing]
  skip_processing = true

# Global headers for all paths - most aggressive no-cache settings possible
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
    X-Content-Type-Options = "nosniff"
    Clear-Site-Data = '"cache","storage"'

# SPA redirect - this is critical for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Specific aggressive no-cache settings for the SovereignAccess page
[[headers]]
  for = "/sovereign-access*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Vary = "*"
