
# Netlify configuration file

[build]
  publish = "dist"
  command = "npm run build"

# Basic SPA configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add cache control headers
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
