
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build && node netlify.js"

# Disable processing to prevent automatic optimizations
[build.processing]
  skip_processing = true

# Environment variables
[build.environment]
  NODE_VERSION = "18.0.0"

# Global headers - aggressive no-cache settings
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Clear-Site-Data = '"cache","storage"'

# Specific no-cache for index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Clear-Site-Data = '"cache","storage"'

# SPA redirect - critical for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
