
# Netlify configuration file

# Define build settings
[build]
  publish = "dist"
  command = "npm run build"

# SPA redirect - This is critical for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
